apiVersion: v1
kind: Pod
metadata:
  name: golang-app
  labels:
    app: golang-app
spec:
  containers:
    - name: golang-app
      image: maniengg/golang-rest:tagVersion
      ports:
        - containerPort: 8093
